packages/enketo-express/locales/src/en/translation-additions.json
packages/enketo-express/locales/src/en/translation.json

for #23 
All strings that OC added should be in its own translations-additions.json file.

moved oc translations to translation additions file

---

packages/enketo-express/public/js/src/module/translator.js

Closes #
-   [x] Editing submissions

OC-22333 Fixed translation cache of element with i18nNumber (upstream #1336)

---

packages/enketo-core/src/js/reasons.js

Closes https://jira.openclinica.com/browse/OC-23197
-   [x] None of the above: Form with RFC
Manual testing.
Previous solutions to set autocomplete off to individual fields doesn't work.
None.
None.

Set autocomplete="off" for RFC fields

---

packages/enketo-express/app/views/styles/component/_print-oc.scss

Closes https://jira.openclinica.com/browse/OC-23674
-   [x] None of the above: print/pdf

OC-23674 Fixed overlapped history text in print/pdf

---

packages/enketo-express/locales/src/de/translation-additions.json
packages/enketo-express/locales/src/de/translation.json

OC-23320: Updated translations

---

packages/enketo-express/locales/src/de/translation-additions.json
packages/enketo-express/locales/src/de/translation.json

OC-23320 update translations

---

packages/enketo-express/locales/src/de/translation-additions.json
packages/enketo-express/locales/src/de/translation.json

OC-23320-update-translations

---

packages/enketo-express/locales/src/de/translation-additions.json

Closes https://jira.openclinica.com/browse/OC-23597

OC-23597 Fixed participate button langs

---

packages/enketo-express/locales/src/de/translation-additions.json

Closes https://jira.openclinica.com/browse/OC-23599

OC-23599 Fixed "Powered by" de translation

---

packages/enketo-core/src/widget/text-print/text-print.js

OC-22314 Mask date field for print/pdf

---

packages/enketo-core/src/js/language.js

Closes https://jira.openclinica.com/browse/OC-22393

OC-22393 form language follow url lang parameter

---

packages/enketo-core/src/widget/text-print/text-print.js

Closes https://jira.openclinica.com/browse/OC-23945

[7.2.0.oc] OC-23945 Fixed print date not displayed

---

packages/enketo-core/src/js/print.js
packages/enketo-core/src/js/repeat.js
packages/enketo-core/src/js/utils.js

Closes https://jira.openclinica.com/browse/OC-23960

[7.2.0.oc] OC-23960 Repeat group buttons in grid theme using icons instead of text

---

packages/enketo-core/src/widget/text-print/text-print.js
packages/enketo-express/public/js/src/module/gui.js

Closes https://jira.openclinica.com/browse/OC-22314

[main] OC-22314 Date value should be masked when printed

---

packages/enketo-express/locales/src/de/translation-additions.json

Closes https://jira.openclinica.com/browse/OC-23599

[7.2.0.oc] OC-23599 Fixed "Powered by" de translation

---

packages/enketo-core/src/js/event.js
packages/enketo-core/src/js/utils.js
packages/enketo-core/src/widget/text-print/text-print.js
packages/enketo-express/public/js/src/module/gui.js

Closes https://jira.openclinica.com/browse/OC-22314

OC-22314 Mask contactdata date field and element placeholder handling

---

packages/enketo-core/src/widget/text-print/text-print.js
packages/enketo-express/public/js/src/module/gui.js

Closes #https://jira.openclinica.com/browse/OC-22314

OC-22314 Fixed issue of dob contactdata handling because masking value is already handled by SR

---

packages/enketo-express/app/lib/pdf.js
packages/enketo-express/app/views/styles/component/_print-oc.scss

Closes https://jira.openclinica.com/browse/OC-24149

Fixed PDF page break issue

---

packages/enketo-core/src/js/widgets-controller.js
packages/enketo-core/src/widget/date/datepicker-extended.js

Closes https://jira.openclinica.com/browse/OC-24166

OC-24166 Multilanguage (es, de, fr) support for datepicker widget

---

packages/enketo-core/src/widget/file/filepicker.js
packages/enketo-express/public/js/src/module/translator.js

Closes https://jira.openclinica.com/browse/OC-24167

OC-24167 Fixed filepicker placeholders to use form language

---

packages/enketo-core/src/js/event.js
packages/enketo-core/src/widget/text-print/text-print.js
packages/enketo-express/public/js/src/module/gui.js

Closes https://jira.openclinica.com/browse/OC-22314

OC-22314 Contactdata Full DOB PDF-masked and Print-unmasked

---

packages/enketo-express/app/views/styles/component/_print-oc.scss

Closes https://jira.openclinica.com/browse/OC-24077

OC-24077 Fixed wrap of long text audit history

---

packages/enketo-core/src/widget/text-print/text-print.js

Closes https://jira.openclinica.com/browse/OC-22314

OC-22314 Fixed contactdata masked pdf and unmasked print

---

packages/enketo-core/src/js/form.js

Closes https://jira.openclinica.com/browse/OC-25827
-   [x] Online form submission

OC-25827 Fixed repeats not picking up repeat_count from calculation value
